### ISSUE TITLE
Symbolic Algebra broken

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/ProvingGround#136]
This may have broken with the spire version update. Not covered by tests, but tut gives the following
```
[tut] *** Error reported at /home/gadgil/code/ProvingGround/mantle/src/main/tut/SymbolicAlgebra.md:113
java.lang.StackOverflowError
  at scala.util.Try$.apply(Try.scala:210)
  at provingground.HoTT$.$anonfun$evalSym$1(HoTT.scala:454)
  at provingground.HoTT$.$anonfun$symSubs$1(HoTT.scala:468)
  at provingground.ScalaRep$RepSymbObj.subs(ScalaRep.scala:303)
  at provingground.ScalaRep$RepSymbObj.subs(ScalaRep.scala:291)
  at provingground.HoTT$Subs.replace(HoTT.scala:135)
  at provingground.HoTT$Subs.replace$(HoTT.scala:118)
  at provingground.ScalaRep$RepSymbObj.replace(ScalaRep.scala:291)
  at provingground.SymbolicCRing$SigmaTerm.$anonfun$subs$1(SymbolicCRig.scala:91)
  at scala.collection.immutable.List.map(List.scala:272)
  at provingground.SymbolicCRing$SigmaTerm.subs(SymbolicCRig.scala:91)
  at provingground.SymbolicCRing$SigmaTerm.subs(SymbolicCRig.scala:77)
  at provingground.HoTT$Subs.replace(HoTT.scala:135)
  at provingground.HoTT$Subs.replace$(HoTT.scala:118)
  at provingground.SymbolicCRing$SigmaTerm.replace(SymbolicCRig.scala:77)
  at provingground.HoTT$.lmbda(HoTT.scala:1700)
  at provingground.HoTT$.composition(HoTT.scala:1740)
  at provingground.SymbolicCRing$sum$.act(SymbolicCRig.scala:308)
  at provingground.SymbolicCRing$sum$.act(SymbolicCRig.scala:286)
  at provingground.HoTT$FuncLike.apply(HoTT.scala:1065)
  at provingground.HoTT$FuncLike.apply$(HoTT.scala:1059)
  at provingground.SymbolicCRing$sum$.apply(SymbolicCRig.scala:286)
  at provingground.SymbolicCRing$SigmaTerm.$anonfun$subs$2(SymbolicCRig.scala:92)
  at scala.collection.immutable.List.reduceRight(List.scala:86)
  at provingground.SymbolicCRing$SigmaTerm.subs(SymbolicCRig.scala:92)
  at provingground.SymbolicCRing$SigmaTerm.subs(SymbolicCRig.scala:77)
...
```
This happens when simplifying `factorial(k + 2)`

**Comment by siddhartha-gadgil** [comment]
Crashes for `(k+ 2) * factorial(k + 1)` after computing `factorial(k + 1)` fine.

**Comment by siddhartha-gadgil** [comment]
Crashes even for:
```
val y = (m + 1) * n * factorial(k)
y: LocalTerm = SigmaTerm(Set(PiTerm(Map(n : (Nat.Typ) -> 1, (<function1>) (k : (Nat.Typ)) : (Nat.Typ) -> 1)), PiTerm(Map((<function1>) (k : (Nat.Typ)) : (Nat.Typ) -> 1, m : (Nat.Typ) -> 1, n : (Nat.Typ) -> 1))))
y + y
...
```

**Comment by siddhartha-gadgil** [comment]
This was accidentally caused by redefining composition using `lmbda` not `LambdaFixed`. Works fine now.
