### ISSUE TITLE
Clean up universes

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/ProvingGround#207]
* As a quick fix for lean, universes were declared equal, though this is unsound.
* One should instead apply functions while running with lean allowing shifting of universes to match the domain and the type of the argument.

**Comment by siddhartha-gadgil** [comment]
* There is a case which shows the error in the tests, `natnoct` from lean (no confusion type for natural numbers).
* In this case, a simplified induction is used, which is defined for type families `P: Nat ->: Type` but applied to a higher type family.
* Most errors may be of this form.

**Comment by siddhartha-gadgil** [comment]
* Potential fix: for lambdas only have a modified check before application that allows resizing universes.
* Implemented in 2d2a435e97ad67615e on the branch _resized_

**Comment by siddhartha-gadgil** [comment]
* Fails for `bin_tree.no_confusion`, because of `bin_tree` having modified type.
* Should not modify types when replacing symbolic objects, at least when the types are universes

**Comment by siddhartha-gadgil** [comment]
On removing the replacement of types, the simplest test failure was

Sigma-type
- should be defined property *** FAILED ***
```scala
  ((a : A ) ~> ((ba : (B(_ : A)) (a) ) ~> (((D(_ : Σ(a : A, B(a)))) (a)) (ba)))) → ((((aa) , (bbaa)) : ∑((a :  A) ↦ ((B(_ : A)) (a))) ) ~> (((D(_ : Σ(a : A, B(a)))) (aa)) (bbaa))) 
  did not equal 
  ((a : A ) ~> ((ba : (B(_ : A)) (a) ) ~> (((D(_ : Σ(a : A, B(a)))) (a)) (ba)))) → (((((a, ba)_1) , ((a, ba)_2)) : ∑((a :  A) ↦ ((B(_ : A)) (a))) ) ~> (((D(_ : Σ(a : A, B(a)))) ((a, ba)_1)) ((a, ba)_2))) 
```
(IntegrationSpec.scala:667)

**Comment by siddhartha-gadgil** [comment]
Issue seems to be that if a special symbol such as a _projection_ is wrapped in an inner symbol, then changing it has no effect on the full symbol, unless we go through types.

**Comment by siddhartha-gadgil** [comment]
If we allow replacement with different types, we should have types replaced. The question is why this is needed.

**Comment by siddhartha-gadgil** [comment]
A full stack trace, showing error during replace, perhaps an incorrect index.
```scala
provingground.HoTT$FuncLike.apply(HoTT.scala:1400),
  provingground.HoTT$FuncLike.apply$(HoTT.scala:1399),
  provingground.HoTT$SymbolicFunc.apply(HoTT.scala:1593),
  provingground.induction.TypFamilyPtn$FuncTypFamily.typ(TypFamily.scala:180),
  provingground.induction.TypFamilyPtn$FuncTypFamily.typ(TypFamily.scala:165),
  provingground.induction.TypFamilyPtn$DepFuncTypFamily.typ(TypFamily.scala:247),
  provingground.induction.TypFamilyPtn$DepFuncTypFamily.typ(TypFamily.scala:231),
  provingground.induction.IndexedInductiveDefinition$Funcs.<init>(InductiveCaseDefinition.scala:141),
  provingground.induction.IndexedInductiveDefinition$Funcs$.apply(InductiveCaseDefinition.scala:139),
  provingground.induction.IndexedInductiveDefinition$Funcs.subs(InductiveCaseDefinition.scala:175),
  provingground.induction.IndexedInductiveDefinition$Funcs.subs(InductiveCaseDefinition.scala:139),
  provingground.HoTT$Subs.replace(HoTT.scala:183),
  provingground.HoTT$Subs.replace$(HoTT.scala:154),
  provingground.induction.IndexedInductiveDefinition$Funcs.replace(InductiveCaseDefinition.scala:139),
  provingground.HoTT$LambdaLike.subs(HoTT.scala:1752),
  provingground.HoTT$LambdaLike.subs$(HoTT.scala:1745),
  provingground.HoTT$LambdaTerm.subs(HoTT.scala:1771),
  provingground.HoTT$LambdaTerm.subs(HoTT.scala:1771),
  provingground.HoTT$Subs.replace(HoTT.scala:183),
  provingground.HoTT$Subs.replace$(HoTT.scala:154),
  provingground.HoTT$LambdaTerm.replace(HoTT.scala:1771),
  provingground.HoTT$.lambda(HoTT.scala:2011),
  provingground.HoTT$RichTerm.$colon$tilde$greater(HoTT.scala:2731),
  provingground.induction.TypFamilyMap$DepFuncTypFamilyMap.iterDepFunc(TypFamily.scala:583),
  provingground.induction.TypFamilyMap$DepFuncTypFamilyMap.iterDepFunc(TypFamily.scala:534),
  provingground.induction.IndexedInductiveDefinition.iterDepFunc$lzycompute(InductiveCaseDefinition.scala:178),
  provingground.induction.IndexedInductiveDefinition.iterDepFunc(InductiveCaseDefinition.scala:178),
  provingground.induction.IndexedConstructorSeqMap.induc(IndexedConstructorSequence.scala:90),
  provingground.induction.IndexedConstructorSeqDom.induc(IndexedConstructorSequence.scala:546),
```

**Comment by siddhartha-gadgil** [comment]
Confirmed that this is an `index` related issue
```scala
provingground.induction.IndexedInductiveDefinition#Funcs#dom:142 ind: SymbTyp(Name("$argjxz"), 0) :: SymbolicFunc(Name("$argjyc"), SymbTyp(Name("$argjxz"), 0), Universe(0)) :: HNil
provingground.induction.IndexedInductiveDefinition#Funcs#dom:142 ind: SymbTyp(Name("$argjxz"), 0) :: SymbolicFunc($argjyc, SymbTyp(Name("$argjxz"), 0), Universe(0)) :: HNil
provingground.induction.IndexedInductiveDefinition#Funcs#dom:142 ind: SymbTyp(Name("$argjxz"), 0) :: SymbolicFunc($argjyc, SymbTyp($argjxz, 0), Universe(0)) :: HNil
- should be defined properly *** FAILED ***
  provingground.HoTT$ApplnFailException: function (Σ) ($argjxz) with domain(optional) Some(($argjxz) → (𝒰 _0)) cannot act on given term $argjyc with type ($argjxz) → (𝒰 _0)
  at provingground.HoTT$FuncLike.apply(HoTT.scala:1400)
  at provingground.HoTT$FuncLike.apply$(HoTT.scala:1399)
  at provingground.HoTT$SymbolicFunc.apply(HoTT.scala:1593)
  at provingground.induction.TypFamilyPtn$FuncTypFamily.typ(TypFamily.scala:180)
  at provingground.induction.TypFamilyPtn$FuncTypFamily.typ(TypFamily.scala:165)
  at provingground.induction.TypFamilyPtn$DepFuncTypFamily.typ(TypFamily.scala:247)
  at provingground.induction.TypFamilyPtn$DepFuncTypFamily.typ(TypFamily.scala:231)
  at provingground.induction.IndexedInductiveDefinition$Funcs.<init>(InductiveCaseDefinition.scala:143)
  at provingground.induction.IndexedInductiveDefinition$Funcs$.apply(InductiveCaseDefinition.scala:139)
  at provingground.induction.IndexedInductiveDefinition$Funcs.subs(InductiveCaseDefinition.scala:178)
  ...
```
and we see a similar error in the other case that does not involve special types.

**Comment by siddhartha-gadgil** [comment]
* It is correct semantics to have type replacement, the above are _not_ bugs.
* should have a workaround for universe parameters, for example more permissive formal application.

**Comment by siddhartha-gadgil** [comment]
* `bin_tree.no_confusion` has been corrected in ad2d9a02102
* A more complicated error is seen in `decidable.rec_on_true`, perhaps because of non simplification if universes do not match.

**Comment by siddhartha-gadgil** [comment]
Some of the output
```scala
@ apf.domOpt.get 
res20: Typ[Term] = ∏(_ : 'u){ induc_{ decidable('u) ; (_ : decidable('u)) ↦ 𝒰  }('x)('w)(_) }

@ apf.argType 
res21: Typ[Term] = ('u → 'w(_))

@ val dt = p.defnMap(trepplein.Name("decidable", "is_true")) 
dt: Term = decidable.is_true

@ dt.typ 
res25: Typ[U] = ∏('c : Prop){ ('c → decidable('c)) }

@ val df = p.defnMap(trepplein.Name("decidable", "is_false")) 
df: Term = decidable.is_false

@ df.typ 
res27: Typ[U] = ∏('d : Prop){ (('d → false) → decidable('d)) }

@ apf.domOpt.get 
res28: Typ[Term] = ∏(_ : 'u){ induc_{ decidable('u) ; (_ : decidable('u)) ↦ 𝒰  }('x)('w)(_) }

@ val d = p.defnMap(trepplein.Name("decidable")) 
d: Term = decidable

@ d.typ 
res30: Typ[U] = (Prop → 𝒰 )
```

**Comment by siddhartha-gadgil** [comment]
This is a separate issue, regarding formal application with propositions.
